---
- name: Install PyMySQL for Ansible MySQL modules
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Ensure MySQL is started and enabled
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  notify: Restart mysql

- name: Set root password and enable password authentication
  ansible.builtin.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
    plugin: mysql_native_password

- name: Ensure database is present
  ansible.builtin.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Ensure MySQL user exists
  ansible.builtin.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
